### ISSUE TITLE
In 1.982, the cpu temperature is checked from the wrong sensor

### ISSUE THREAD

**Issue by vladns** [virtualmin/authentic-theme#1567]
![cpu](https://user-images.githubusercontent.com/22105830/143763393-4c86fb20-039b-44b8-8556-210902acc16b.png)
After upgrading to 1.982 (from 1.981), the processor temperature is read from the wrong sensor. It constantly shows 127 degrees. Sensors output:
```
nct6779-isa-0a10
Adapter: ISA adapter
...
SYSTIN:                 +52.0°C  (high =  +0.0°C, hyst =  +0.0°C)  ALARM  sensor = CPU diode
CPUTIN:                +127.5°C  (high = +80.0°C, hyst = +75.0°C)  ALARM  sensor = CPU diode
...

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +48.0°C  (high = +86.0°C, crit = +96.0°C)
Core 0:        +47.0°C  (high = +86.0°C, crit = +96.0°C)
Core 1:        +47.0°C  (high = +86.0°C, crit = +96.0°C)
Core 2:        +47.0°C  (high = +86.0°C, crit = +96.0°C)
Core 3:        +46.0°C  (high = +86.0°C, crit = +96.0°C)
```
Possibly the CPUTIN value is taken (not sure). The previous version had 4 Core 0/1/2/3 sensors.

**Comment by iliarostovtsev** [comment]
Hi,

This is incorrect output. CPUIN can never be higher than core temp, unless your motherboard sensor is broken.

Also, `coretemp isa` should always come first.

**Comment by iliarostovtsev** [comment]
Also, I have checked the code, and I do not see how it would be possible, as `Package id` always prioritised to using sensors from MB.

You are welcome to share complete `sensors` command output as text and I will take a closer look.

**Comment by vladns** [comment]
Nevertheless, it somehow worked before :).
```
nct6779-isa-0a10
Adapter: ISA adapter
Vcore:                 912.00 mV (min =  +0.00 V, max =  +1.74 V)
in1:                   1000.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
AVCC:                    3.39 V  (min =  +2.98 V, max =  +3.63 V)
+3.3V:                   3.38 V  (min =  +2.98 V, max =  +3.63 V)
in4:                     1.13 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in5:                   800.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in6:                     1.07 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
3VSB:                    3.42 V  (min =  +2.98 V, max =  +3.63 V)
Vbat:                    3.36 V  (min =  +2.70 V, max =  +3.63 V)
in9:                   1000.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in10:                  432.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in11:                   32.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in12:                  1000.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in13:                  672.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in14:                  800.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
fan1:                     0 RPM  (min =    0 RPM)
fan2:                   686 RPM  (min =    0 RPM)
fan3:                     0 RPM  (min =    0 RPM)
fan4:                     0 RPM  (min =    0 RPM)
fan5:                     0 RPM  (min =    0 RPM)
SYSTIN:                 +52.0 C  (high =  +0.0 C, hyst =  +0.0 C)  ALARM  sensor = CPU diode
CPUTIN:                +127.5 C  (high = +80.0 C, hyst = +75.0 C)  ALARM  sensor = CPU diode
AUXTIN0:                +22.0 C    sensor = thermistor
AUXTIN1:                +59.0 C    sensor = thermistor
AUXTIN2:               +127.0 C    sensor = thermistor
AUXTIN3:                -50.0 C    sensor = thermal diode
PECI Agent 0:           +47.5 C  
PCH_CHIP_CPU_MAX_TEMP:   +0.0 C  
PCH_CHIP_TEMP:           +0.0 C  
PCH_CPU_TEMP:            +0.0 C  
intrusion0:            ALARM
intrusion1:            ALARM
beep_enable:           disabled

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +27.8 C  (crit = +101.0 C)
temp2:        +29.8 C  (crit = +101.0 C)

ath10k_hwmon-pci-0500
Adapter: PCI adapter
temp1:        +45.0 C  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +47.0 C  (high = +86.0 C, crit = +96.0 C)
Core 0:        +47.0 C  (high = +86.0 C, crit = +96.0 C)
Core 1:        +47.0 C  (high = +86.0 C, crit = +96.0 C)
Core 2:        +46.0 C  (high = +86.0 C, crit = +96.0 C)
Core 3:        +46.0 C  (high = +86.0 C, crit = +96.0 C)
```

**Comment by iliarostovtsev** [comment]
Fixed.

https://github.com/webmin/webmin/commit/1e0cfa5b23c37d2c59c610a62922234e107b7891

**Comment by vladns** [comment]
I still see this error. Where should this fix be applied? Webmin 1.983, Authentic theme version 19.84.6.

**Comment by iliarostovtsev** [comment]
It _must_ be fixed with Webmin 1.983. Have you refreshed system information (top right circular arrow button) from Dashboard or right side slider?

**Comment by vladns** [comment]
Sorry, it was not true, I deleted the message. The problem was really resolved, but not immediately, so he hurried to answer.
